# Generated by Django 4.0.1 on 2028-01-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='address',
            field=models.TextField(default='', max_length=255),
        ),
    ]
