# Generated by Django 4.0.1 on 2023-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0002_order_consumer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='name_of_establishment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
