# Generated by Django 4.0.1 on 2023-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0003_seller_name_of_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email_address_of_establishment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cac_document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='farm_picture1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='farm_picture2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='farm_picture3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='farm_picture4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='farm_picture5',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
