# Generated by Django 4.0.1 on 2023-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0004_seller_email_address_of_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
