# Generated by Django 4.0.1 on 2023-11-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0005_seller_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='email_address_of_establishment',
            new_name='email',
        ),
    ]
