# Generated by Django 4.0.1 on 2023-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromarkethub', '0006_rename_email_address_of_establishment_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='picture1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produce',
            name='picture2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produce',
            name='picture3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produce',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
